package uk.ac.liv.c3connector.ui;


///SAM: using StartupWizard's code


import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Random;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

import uk.ac.liv.c3connector.DistributedPersonalAnnos;
import uk.ac.liverpool.fab4.Fab4utils;
import uk.ac.liverpool.fab4.PersonalAnnos;


public class DocumentInfoRequester extends javax.swing.JDialog{


	/**
	 * "0" when complete bib is needed, else: "ab", a:0 if doi needed else 1, b:0 if keywords needed else 1
	 */
	public static String BibNeededOrDOIkeywords; 
//	DistributedPersonalAnnos da;	
//	public static String newUrl;
	public static String bibtex;
	public static String doi;
	public static String keywords;
	
	String defaultBib = "Copy and paste an available BibTex citation or try the following fields: \n" +
	"@bibtype{someid,\n" +
	"title = { }, \n" +
	"authors = { }, \n" +
	"DOI = { }, \n" +
	"keywords = { }, \n" +
	"..." +
	"}";
	
	//private static final long serialVersionUID = 6532313365019485552L;
	
	public DocumentInfoRequester(/*DistributedPersonalAnnos da,*/ java.awt.Frame parent, boolean modal, /*String uri,*/ String needed) {
		super(parent, modal);
//		this.da = da;
		
		if(needed.equals("0"))
			askForBibAndUrl(/*uri*/);	
		else{
			boolean askDoi = true;
			boolean askKeys = true;
			if(needed.startsWith("1"))
				askDoi = false;
			if(needed.endsWith("1"))
				askKeys = false;
			askForDOIorKeywords(askDoi, askKeys);
		}

		if (Fab4utils.getJavaVersion()>=1.5f)
			setAlwaysOnTop(true);
		
		setLocationRelativeTo(null);
		setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	
	private void askForBibAndUrl(/*String uri*/){
		
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		
		jLabel_bibtex = new javax.swing.JLabel();
//		jLabel_url = new javax.swing.JLabel();
		
		
//		jText_url = new javax.swing.JTextField();
		
		/*jText_url.setText(uri);*/
		
		jText_bibtex = new javax.swing.JTextArea(defaultBib,10,40);
		JScrollPane scrol = new JScrollPane(jText_bibtex);
		/*Dimension minimumSize = new Dimension(100, 20) ;
		scrol.setMinimumSize(minimumSize);*/
//		scrol.setSize(40, 20);
		
		jLabel5 = new javax.swing.JLabel();
		jText12 = new javax.swing.JTextField();
		jButton1_ok = new javax.swing.JButton();
		jButton2_cancel = new javax.swing.JButton();
		
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		
		jLabel1.setText("Please help us collect public annotations and information about this resource with providing:");
//		jLabel1.setSize(100, 5);
		
		jLabel_bibtex.setText("BibTex:");
		
//		jLabel_url.setText("URL (Please provide a web address):");
				
		
		jText_bibtex.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		/*jText_url.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});*/
				
		jText12.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		jText_bibtex.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		/*jText_url.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});*/
				
		
		jText12.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});

		jLabel5.setText("User identifier:");
		jLabel5.setVisible(false);
		jText12.setVisible(false);
		
		jButton1_ok.setText("Done");
		jButton1_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1_ok_ActionPerformed(evt);
			}
		});

		
		
		//jButton2_later.setText("later");
		jButton2_cancel.setText("Not now");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)								
														
									.add(jLabel_bibtex)
//									.add(jLabel_url)
									
									.add(jLabel5)
							)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
																.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
																		
//																		.add(jLogButtonSignUp)
																		.add(jButton2_cancel)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
																		
																		.add(jButton1_ok)
																		)
																		.add(jText12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		/*.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField3_email, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jTextField10_org, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		*/
																		
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, /*jText_bibtex*/ scrol, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
//																		.add(jText_url, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		/*.add(org.jdesktop.layout.GroupLayout.TRAILING, jPass_cpass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField11_name, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		
																		.add(jTextField_aff, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField_des, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)*/
																		)
																		
																		
																		.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jLabel1)
						.add(22, 22, 22)
						
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(/*jText_bibtex*/ scrol, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_bibtex))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						/*.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jText_url, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_url))*/
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)																			
												
												.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jText12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel5))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jButton1_ok)
																.add(jButton2_cancel)
//																.add(jLogButtonSignUp)
																)
																.addContainerGap())
		);
		
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1 , org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1 , org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		jButton1_ok.setEnabled(false);
		//jButton1.setToolTipText("fill in the fields above, at least the required ones, or press later");
		jButton1_ok.setToolTipText("If you fill the above, other will have more chance to find your annotations and you will be more lucky to see theirs!");
		
		jButton2_cancel.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				cancel();
			}			

		});
		
		setTitle("Resource details...");
//		setSize(200, 50);
		pack();

	}
	

private void askForDOIorKeywords(boolean askDOI, boolean askKeys){
	
	if(!askDOI && !askKeys){
		dispose();
		return;
	}
	
		jPanel1_2 = new javax.swing.JPanel();
		jLabel1_2 = new javax.swing.JLabel();
		
		jLabel_keys_2 = new javax.swing.JLabel();
		jLabel_doi_2 = new javax.swing.JLabel();
		
		
		jText_doi_2 = new javax.swing.JTextField();
		
		jText_keys_2 = new javax.swing.JTextArea(8,5);
		
		jLabel5_2 = new javax.swing.JLabel();
		jText12_2 = new javax.swing.JTextField();
		jButton1_ok_2 = new javax.swing.JButton();
		jButton2_cancel_2 = new javax.swing.JButton();
		
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		jLabel1_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		
		jLabel1_2.setText("Please help us collect public annotations and information about this resource with providing:");		
		
		jLabel_keys_2.setText("Keywords: (Separate keywords with ';')");
		
		jLabel_doi_2.setText("DOI:");
				
		
		jText_keys_2.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		jText_doi_2.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
				
		jText12_2.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		jText_keys_2.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		jText_doi_2.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
				
		
		jText12_2.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});

		jLabel5_2.setText("User identifier:");
		jLabel5_2.setVisible(false);
		jText12_2.setVisible(false);
		
		jButton1_ok_2.setText("Done");
		jButton1_ok_2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1_ok_ActionPerformed_2(evt);
			}
		});

		
		
		//jButton2_later.setText("later");
		jButton2_cancel_2.setText("Not now");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1_2);
		jPanel1_2.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jLabel1_2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)								
														
									.add(jLabel_keys_2)
									.add(jLabel_doi_2)
									
									.add(jLabel5_2)
							)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
																.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
																		
//																		.add(jLogButtonSignUp)
																		.add(jButton2_cancel_2)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
																		
																		.add(jButton1_ok_2)
																		)
																		.add(jText12_2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jText_keys_2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jText_doi_2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)																		
																		)
																		
																		.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jLabel1_2)
						.add(22, 22, 22)
						
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jText_keys_2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_keys_2))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jText_doi_2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_doi_2))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)																			
												
												.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jText12_2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel5_2))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jButton1_ok_2)
																.add(jButton2_cancel_2)
//																.add(jLogButtonSignUp)
																)
																.addContainerGap())
		);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1_2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1_2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		jButton1_ok_2.setEnabled(false);
		//jButton1.setToolTipText("fill in the fields above, at least the required ones, or press later");
		jButton1_ok_2.setToolTipText("If you fill any of the above, other will have more chance to find your annotations and you will be more lucky to see theirs!");
		
		jButton2_cancel_2.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				cancel();
			}			

		});
		
		if(!askDOI){
			jLabel_doi_2.setVisible(false);
			jText_doi_2.setVisible(false);
		}
		
		if(!askKeys){
			jLabel_keys_2.setVisible(false);
			jText_keys_2.setVisible(false);
		}
		
		setTitle("Resource details...");
		pack();

	}

	

	private void cancel() {		
		dispose();
//		DocumentInfoRequester.CANCEL = true; //in order to stop reloading
		//da.notify();
	}
	
	
	void focus() {		
		if(jButton1_ok != null)
			jButton1_ok.setEnabled(true);
		else
			jButton1_ok_2.setEnabled(true);
	}

	
	
	void jButton1_ok_ActionPerformed(java.awt.event.ActionEvent evt) {
		
//		String url = jText_url.getText();
		String bib = jText_bibtex.getText();
		
		if( !bib.equals(defaultBib) ){
			bibtex = bib;
		}
		/*if( url != null && !url.equals(""))
			newUrl = url;*/
		
		dispose();
		
	}
	
	void jButton1_ok_ActionPerformed_2(java.awt.event.ActionEvent evt) {
		
		doi = jText_doi_2.getText();
		if(doi != null && doi.equals(""))
			doi = null;
				
		keywords = jText_keys_2.getText();
		if(keywords !=null && keywords.equals(""))
			keywords = null;
				
		dispose();
		
	}
	

	// Variables declaration - do not modify	
	
	///ask for bib:
	private javax.swing.JButton jButton1_ok;	
	private javax.swing.JButton jButton2_cancel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jText12;
//	private javax.swing.JButton jLogButtonSignUp;
	private javax.swing.JLabel jLabel_bibtex;
//	private javax.swing.JLabel jLabel_url;
	private javax.swing.JTextArea jText_bibtex;
//	private JTextField jText_url;

	private javax.swing.JButton jButton1_ok_2;	
	private javax.swing.JButton jButton2_cancel_2;
	private javax.swing.JLabel jLabel1_2;
	private javax.swing.JLabel jLabel5_2;
	private javax.swing.JPanel jPanel1_2;
	private javax.swing.JTextField jText12_2;
//	private javax.swing.JButton jLogButtonSignUp;
	private javax.swing.JLabel jLabel_keys_2;
	private javax.swing.JLabel jLabel_doi_2;
	private javax.swing.JTextArea jText_keys_2;
	private JTextField jText_doi_2;

	// End of variables declaration			

}
