/*******************************************************************************
 *
 *  * Copyright (C) 2007, 2010 - The University of Liverpool
 *  * This program is free software; you can redistribute it and/or modify it under the terms
 *  * of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License,
 *  * or (at your option) any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 *  * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *  * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *  *
 *  * Author: Fabio Corubolo
 *  * Email: corubolo@gmail.com
 * 
 *******************************************************************************/



package uk.ac.liv.c3connector.ui;


import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.ArrayList;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import uk.ac.liv.c3connector.DistributedPersonalAnnos;
import uk.ac.liv.c3connector.TrustedIdentity;
import uk.ac.liverpool.fab4.SWListModel;

/**
 *
 * This is the preferences dialog for the Distributed Annotations component. It's quite rich and allows the insertion of new trusted parties.
 * 
 *
 * @author  fabio Corubolo
 */
public class PreferencesDialog extends Dialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3824288032142633930L;

	private Frame parent;

	private SWListModel trustList;

	private ArrayList <TrustedIdentity>trustCopy;

	private DistributedPersonalAnnos da;
	/** Creates new form PreferencesDialog */
	public PreferencesDialog(DistributedPersonalAnnos da,java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.parent=parent;
		this.da = da;
		setTitle("Preferences");
		initComponents();

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jLabel13 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jPanel6 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		jTextField13 = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		jTextField14 = new javax.swing.JTextField();
		jPasswordField4 = new javax.swing.JPasswordField();
		jLabel23 = new javax.swing.JLabel();
		jButton9 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextArea2 = new javax.swing.JTextArea();
		jLabel10 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jCheckBox5 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox1 = new javax.swing.JCheckBox();
		///SAM
		jCheckBoxBib = new javax.swing.JCheckBox();
		///
		jLabel2 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jCheckBox6 = new javax.swing.JCheckBox();
		jCheckBox7 = new javax.swing.JCheckBox();
		jCheckBox8 = new javax.swing.JCheckBox();
		jPanel3 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		jButton8 = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel3 = new javax.swing.JLabel();
		jButton7 = new javax.swing.JButton();
		jTextField11 = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jPanel9 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setBackground(new java.awt.Color(238, 238, 238));
		addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				if (preferencesChanged()){
					int n = JOptionPane.showConfirmDialog(evt.getComponent(), "Save the changes?", "Attention",
							JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);//YES_NO_CANCEL_OPTION
							if (n==0) {
								closeDialog();
								savePrefs();
							} else if (n==1)
								closeDialog();
				} else
					closeDialog();
			}
		});
		jLabel1.setFont(new java.awt.Font("Dialog", 1, 16));
		jLabel1.setText("Annotation preferences");

		jTabbedPane1.setFocusTraversalPolicyProvider(true);
		///SAM
		if(DistributedPersonalAnnos.getCurrentRemoteServer().equals("REST"))
			jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Search address:"));
		else ///
			jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("SRU address:"));
		
		jPanel5.setFocusTraversalPolicyProvider(true);
		jPanel5.setEnabled(true);
		
		///SAM
		if(DistributedPersonalAnnos.getCurrentRemoteServer().equals("REST"))
			jLabel11.setText("Search URL: ");
		else ///
			jLabel11.setText("SRU URL: ");
		
		jTextField6.setText("**");
		jTextField6.setFocusCycleRoot(true);
		jTextField6.setFocusTraversalPolicyProvider(true);
		jTextField6.setEditable(true);
		jTextField6.setEnabled(true);
		//jTextField6.setNextFocusableComponent(jTextField7);

		jLabel12.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel12.setText("userId");

		jTextField7.setFocusTraversalPolicyProvider(true);

		jPasswordField2.setFocusTraversalPolicyProvider(true);
		jPasswordField2.setEnabled(false);
		jLabel13.setFont(new java.awt.Font("Dialog", 0, 12));
		jLabel13.setText("Password");

		jButton5.setText("test");
		jButton5.setEnabled(false);
		jButton5.setFocusTraversalPolicyProvider(true);
		jButton5.setMargin(new java.awt.Insets(0, 6, 0, 6));
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				testSRW(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(
				jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel5Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jPanel5Layout.createSequentialGroup()
										.add(jLabel11)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
												.add(jPanel5Layout.createSequentialGroup()
														.add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jLabel13)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPasswordField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jButton5))
														.add(jTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
														.add(jPanel5Layout.createSequentialGroup()
																.add(jLabel12)
																.add(222, 222, 222)))
																.addContainerGap())
		);
		jPanel5Layout.setVerticalGroup(
				jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel5Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel11)
								.add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel12)
										.add(jLabel13)
										.add(jPasswordField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jButton5))
										.addContainerGap(21, Short.MAX_VALUE))
		);

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Annotation Server "));
		jLabel21.setText("URL: ");

		jTextField13.setText("http://bodoni.lib.liv.ac.uk:8080/AnnotationConnector/services/AnnotationServer");
		jTextField13.setFocusTraversalPolicyProvider(true);

		jLabel22.setText("userId");

		jTextField14.setFocusTraversalPolicyProvider(true);

		jPasswordField4.setFocusTraversalPolicyProvider(true);

		jLabel23.setText("Password");

		jButton9.setText("default");
		jButton9.setFocusTraversalPolicyProvider(true);
		jButton9.setMargin(new java.awt.Insets(0, 6, 0, 6));
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				testConnector(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel6Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jPanel6Layout.createSequentialGroup()
										.add(jLabel21)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
												.add(jPanel6Layout.createSequentialGroup()
														.add(jTextField14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jLabel23)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPasswordField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jButton9))
														.add(jTextField13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
														.add(jPanel6Layout.createSequentialGroup()
																.add(jLabel22)
																.add(222, 222, 222)))
																.addContainerGap())
		);
		jPanel6Layout.setVerticalGroup(
				jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel6Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel21)
								.add(jTextField13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel22)
										.add(jLabel23)
										.add(jPasswordField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jTextField14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jButton9))
										.addContainerGap(21, Short.MAX_VALUE))
		);

		
		///SAM
		JPanel serverPanel = new JPanel();
		serverPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose server:"));
		serverPanel.setFocusTraversalPolicyProvider(true);
		serverPanel.setEnabled(true);
		
		final JRadioButton rest = new JRadioButton("CLR Server");
		final JRadioButton rdf = new JRadioButton("Fab4 Server");
		
		if(DistributedPersonalAnnos.getCurrentRemoteServer().equals("REST"))
			rest.setSelected(true);
		else if(DistributedPersonalAnnos.getCurrentRemoteServer().equals("RDF"))
			rdf.setSelected(true);
		
		rest.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DistributedPersonalAnnos.setCurrentRemoteServer("REST");
				if(!DistributedPersonalAnnos.getCurrentRemoteServer().equals("REST"))
					rest.setEnabled(false);
				else
					serverChanged = true;
				jTextField6.setText(DistributedPersonalAnnos.searchServiceURL);
				jTextField13.setText(DistributedPersonalAnnos.publishServiceURL);
			}
		});
		
		rdf.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DistributedPersonalAnnos.setCurrentRemoteServer("RDF");
				if(!DistributedPersonalAnnos.getCurrentRemoteServer().equals("RDF"))
					rdf.setEnabled(false);
				else
					serverChanged = true;
				jTextField6.setText(DistributedPersonalAnnos.searchServiceURL);
				jTextField13.setText(DistributedPersonalAnnos.publishServiceURL);
			}
		});
		
		ButtonGroup choices = new ButtonGroup();
		choices.add(rest);
		choices.add(rdf);
		
		JPanel radioPanel = new JPanel(new GridLayout(1, 0));
		radioPanel.add(rest);
		radioPanel.add(rdf);

		serverPanel.add(radioPanel, BorderLayout.LINE_START);

		///
		
		
		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								///SAM
								.add(serverPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								///
								.add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap())
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						///SAM
						.add(serverPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						///
						.add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(249, 249, 249))
		);
		

		
		jTabbedPane1.addTab("Servers", jPanel2);

		jLabel6.setText("Name");

		jLabel7.setText("E-mail");

		jLabel9.setText("Organisation");

		///SAM
		if(!DistributedPersonalAnnos.getCurrentRemoteServer().equals("REST")){
		///	
		
		jLabel5.setText("Public key:");

		jTextArea2.setColumns(20);
		jTextArea2.setEditable(true);
		jTextArea2.setFont(new java.awt.Font("Dialog", 0, 10));
		jTextArea2.setRows(5);

		jLabel10.setText("path to keystore file");

		jTextField5.setEditable(false);

		jTextField8.setEditable(false);

		jLabel14.setText("path to trusted keys file");

		jButton4.setText("Generate new key pair");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				generateNewKeypair(evt);
			}
		});

		///SAM
		}
		else{
			jLabel5.setVisible(false);
			jTextArea2.setVisible(false);
			jLabel10.setVisible(false);
			jTextField5.setVisible(false);
			jTextField8.setVisible(false);
			jLabel14.setVisible(false);
			jButton4.setVisible(false);
		}
		
		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel4Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jTextArea2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
								.add(jPanel4Layout.createSequentialGroup()
										.add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
												.add(jLabel6)
												.add(jLabel9)
												.add(jLabel7))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
														.add(jTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
														.add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
														.add(jTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
														.add(jLabel5)
														.add(jLabel10)
														.add(jTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
														.add(jLabel14)
														.add(jTextField8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
														.add(jButton4))
														.addContainerGap())
		);
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel4Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel6)
								.add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel9)
										.add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
												.add(jLabel7)
												.add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel5)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jTextArea2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel10)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel14)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jButton4)
												.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		
		///SAM use scorl instead of jPanel4
		JScrollPane scrolPanel4 = new JScrollPane(jPanel4);
//		jTabbedPane1.addTab("Personal", jPanel4);
		jTabbedPane1.addTab("Personal", scrolPanel4);
		///

		jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Annotation display"));
		jCheckBox5.setText("Trusted parties only");
		jCheckBox5.setToolTipText("Only annotations coming from trusted parties");
		jCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox3.setText("Same contents (possibly different format)");
		jCheckBox3.setToolTipText("Shows annotations refering to the same TEXTUAL content (ignoring formatting, images etc.)");
		jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox4.setText("Similar contents");
		jCheckBox4.setToolTipText("Shows annotations refering to similar content");
		jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox2.setText("Same exact document");
		jCheckBox2.setToolTipText("Shows annotations refering to the same exact file");
		jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox1.setText("Same URL");
		jCheckBox1.setToolTipText("Shows annotations refering to the URL being visited");
		jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

		///SAM
		jCheckBoxBib.setText("Same BibTex");
		jCheckBoxBib.setToolTipText("Shows annotations refering to the resources which are known to have same/very similar BibTex");
		jCheckBoxBib.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBoxBib.setMargin(new java.awt.Insets(0, 0, 0, 0));
		///
		
		jLabel2.setText("Show annotation from documents having:");

		jLabel8.setText("Show the following annotation types:");

		jCheckBox6.setText("Fab4");
		jCheckBox6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox7.setText("VoiceMemo");
		jCheckBox7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox8.setText("PlayML");
		jCheckBox8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox8.setMargin(new java.awt.Insets(0, 0, 0, 0));

		org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(
				jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel7Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jLabel2)
								.add(jCheckBox1)
								.add(jCheckBox2)
								.add(jCheckBox4)
								.add(jCheckBox3)
								
								///SAM
								.add(jCheckBoxBib)
								///
								
								.add(jCheckBox5)
								.add(jCheckBox6)
								.add(jCheckBox8)
								.add(jCheckBox7)
								.add(jLabel8))
								.addContainerGap(107, Short.MAX_VALUE))
		);
		jPanel7Layout.setVerticalGroup(
				jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel7Layout.createSequentialGroup()
						.add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jCheckBox1)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jCheckBox2)
						.add(9, 9, 9)
						.add(jCheckBox4)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jCheckBox3)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						
						///SAM
						.add(jCheckBoxBib)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						///
						
						.add(jCheckBox5)
						.add(16, 16, 16)
						.add(jLabel8)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jCheckBox6)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jCheckBox8)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jCheckBox7)
						.addContainerGap(29, Short.MAX_VALUE))
		);

		///SAM
		JScrollPane scrolPane = new JScrollPane(jPanel7);
		///
		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						///SAM change jPanel to scrolPane
//						.add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.add(scrolPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						///
						.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						///SAM change jPanel to scrolPane						
//						.add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.add(scrolPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						///
						.addContainerGap())
		);
		jTabbedPane1.addTab("Display", jPanel1);

		jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("User information")));
		jButton8.setText("Add / modify");
		jButton8.setMargin(new java.awt.Insets(0, 6, 0, 6));
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addTrustedParty(evt);
			}
		});

		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Dialog", 0, 10));
		jTextArea1.setRows(5);
		jScrollPane3.setViewportView(jTextArea1);

		jLabel3.setText("public key (you can paste one here)");

		jButton7.setText("delete");
		jButton7.setEnabled(false);
		jButton7.setMargin(new java.awt.Insets(0, 6, 0, 6));
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addPkFromFile(evt);
			}
		});

		jLabel18.setText("E-mail");

		jLabel17.setText("Organisation");

		jLabel4.setText("Name");

		org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(
				jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel8Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
								.add(jButton8)
								.add(jPanel8Layout.createSequentialGroup()
										.add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
												.add(jLabel17)
												.add(jLabel18)
												.add(jLabel4))
												.add(28, 28, 28)
												.add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
														.add(jTextField11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
														.add(jTextField10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
														.add(jTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
														.add(jLabel3)
														.add(jButton7))
														.addContainerGap())
		);
		jPanel8Layout.setVerticalGroup(
				jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
						.add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel4)
								.add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel17)
										.add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jLabel18)
												.add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jButton7)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jButton8))
		);

		jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Select a user"));
		jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(jList1);

		org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(
				jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
		);
		jPanel9Layout.setVerticalGroup(
				jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
		);

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
		);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
								.add(org.jdesktop.layout.GroupLayout.LEADING, jPanel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(org.jdesktop.layout.GroupLayout.LEADING, jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap())
		);
		jTabbedPane1.addTab("Trusted parties", jPanel3);

		jButton2.setText("OK");
		jButton2.setAlignmentX(0.5F);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				OKpressed(evt);
			}
		});

		jButton3.setText("Cancel");
		jButton3.setAlignmentX(0.5F);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				CancelPressed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout.createSequentialGroup()
										.add(jButton2)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jButton3))
										.add(jLabel1)
										.add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
										.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jLabel1)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 333, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jButton2)
								.add(jButton3))
								.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		loadPrefs();

		pack();
	}// </editor-fold>

	/**
	 * 
	 */
	@SuppressWarnings("unchecked")
	private void loadPrefs() {
		jTextField6.setText(DistributedPersonalAnnos.searchServiceURL);
		jTextField13.setText(DistributedPersonalAnnos.publishServiceURL);
		jTextField14.setText(DistributedPersonalAnnos.userid);
		jPasswordField4.setText(DistributedPersonalAnnos.pass);
		jTextField1.setText(DistributedPersonalAnnos.author);
		jTextField4.setText(DistributedPersonalAnnos.organisation);
		jTextField2.setText(DistributedPersonalAnnos.email);
		jTextField7.setEnabled(false);
		jPasswordField2.setEnabled(false);
		//jTextField5.setEnabled(true);
		jTextField5.setText(DistributedPersonalAnnos.defksfile.getAbsolutePath());
		jTextField8.setText(DistributedPersonalAnnos.deftrusted.getAbsolutePath());
		jCheckBox1.setSelected(DistributedPersonalAnnos.sameUrl);
		jCheckBox2.setSelected(DistributedPersonalAnnos.sameDigest);
		jCheckBox4.setSelected(DistributedPersonalAnnos.sameLexical);
		jCheckBox3.setSelected(DistributedPersonalAnnos.sameTxtDigest);
		
		///SAM
		jCheckBoxBib.setSelected(DistributedPersonalAnnos.sameBib);
		///
		
		jCheckBox5.setSelected(DistributedPersonalAnnos.trustedParty);
		jCheckBox6.setSelected(DistributedPersonalAnnos.showFab4);
		jCheckBox7.setSelected(DistributedPersonalAnnos.showPlay);
		jCheckBox8.setSelected(DistributedPersonalAnnos.showVoice);



		try {
			jTextArea2.setText(TrustedIdentity.convertTotring(DistributedPersonalAnnos.myTI));
		} catch (IOException e) {
			e.printStackTrace();
		}
		trustCopy = new ArrayList <TrustedIdentity> (DistributedPersonalAnnos.trusted);
		trustList = new SWListModel(trustCopy);
		jList1.setModel(trustList);
		jList1.setCellRenderer(new TILrender());
		jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jList1.addListSelectionListener(new ListSelectionListener() {

			public void valueChanged(ListSelectionEvent e) {
				trustSelected(e);
			}

		});

	}

	/**
	 * @param e
	 */
	protected void trustSelected(ListSelectionEvent e) {
		//3 10 11
		int s = jList1.getSelectedIndex();
		System.out.println(s);
		if (s<0) {
			System.out.println("wsss");
			return;
		}
		TrustedIdentity t = (TrustedIdentity ) trustList.get(s);
		System.out.println(t.getName());
		jTextField3.setText(t.getName());
		jTextField10.setText(t.getOrganisation());
		jTextField11.setText(t.getEmail());
		jButton7.setEnabled(true);

	}

	void savePrefs() {
		//DistributedPersonalAnnos.srwAddress = jTextField6.getText();
		DistributedPersonalAnnos.publishServiceURL = jTextField13.getText();
		DistributedPersonalAnnos.searchServiceURL = jTextField6.getText();
		DistributedPersonalAnnos.userid = jTextField14.getText();
		DistributedPersonalAnnos.pass = new String(jPasswordField4.getPassword());
		DistributedPersonalAnnos.author = jTextField1.getText();
		DistributedPersonalAnnos.organisation = jTextField4.getText();
		DistributedPersonalAnnos.email= jTextField2.getText();
		DistributedPersonalAnnos.sameUrl = jCheckBox1.isSelected();
		DistributedPersonalAnnos.sameDigest= jCheckBox2.isSelected();
		DistributedPersonalAnnos.sameLexical = jCheckBox4.isSelected();
		DistributedPersonalAnnos.sameTxtDigest = jCheckBox3.isSelected();
		
		///SAM
		DistributedPersonalAnnos.sameBib = jCheckBoxBib.isSelected();
		///
		
		DistributedPersonalAnnos.trustedParty = jCheckBox5.isSelected();
		DistributedPersonalAnnos.showFab4 = jCheckBox6.isSelected();
		DistributedPersonalAnnos.showPlay= jCheckBox7.isSelected();
		DistributedPersonalAnnos.showVoice = jCheckBox8.isSelected();
		DistributedPersonalAnnos.trusted = trustCopy;
		da.savePrefs();
	}
	boolean preferencesChanged() {
		
		///SAM
		if(serverChanged)
			return true;
		///
		
		if (
				DistributedPersonalAnnos.publishServiceURL.equals(jTextField13.getText())&&
				DistributedPersonalAnnos.userid.equals( jTextField14.getText())&&
				DistributedPersonalAnnos.searchServiceURL.equals(jTextField6.getText()) &&
				DistributedPersonalAnnos.pass.equals( new String(jPasswordField4.getPassword()))&&
				DistributedPersonalAnnos.author.equals( jTextField1.getText())&&
				DistributedPersonalAnnos.organisation .equals( jTextField4.getText())&&
				DistributedPersonalAnnos.email.equals( jTextField2.getText())&&
				DistributedPersonalAnnos.sameUrl == jCheckBox1.isSelected()&&
				DistributedPersonalAnnos.sameDigest==jCheckBox2.isSelected()&&
				DistributedPersonalAnnos.sameLexical== jCheckBox4.isSelected()&&
				DistributedPersonalAnnos.sameTxtDigest == jCheckBox3.isSelected()&&
				
				///SAM
				DistributedPersonalAnnos.sameBib == jCheckBoxBib.isSelected()&&
				///
				
				DistributedPersonalAnnos.trustedParty == jCheckBox5.isSelected()&&
				DistributedPersonalAnnos.showFab4 == jCheckBox6.isSelected()&&
				DistributedPersonalAnnos.showPlay == jCheckBox7.isSelected()&&
				DistributedPersonalAnnos.showVoice == jCheckBox8.isSelected()&&
				DistributedPersonalAnnos.trusted.equals(trustCopy)
		)
			return false;
		else return true;

	}


	void CancelPressed(java.awt.event.ActionEvent evt) {
		if (preferencesChanged()){
			int n = JOptionPane.showConfirmDialog(this, "Save the changes?", "Attention",
					JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);//YES_NO_CANCEL_OPTION
			if (n==0) {
				closeDialog();
				savePrefs();
			} else if (n==1)
				closeDialog();
		} else
			closeDialog();

	}

	void OKpressed(java.awt.event.ActionEvent evt) {
		savePrefs();
		closeDialog();
	}

	@SuppressWarnings("unchecked") void addTrustedParty(java.awt.event.ActionEvent evt) {
		String t = jTextArea1.getText();
		if (t.length()==0)
			return;
		try {
			TrustedIdentity tn = TrustedIdentity.readTi(t);
			jTextField3.setText(tn.getName());
			jTextField10.setText(tn.getOrganisation());
			jTextField11.setText(tn.getEmail());
			//			DistributedPersonalAnnos.trusted.add(tn);
			trustList.add(tn);
			jList1.setSelectedValue(tn, true);
		} catch (IOException e) {
			JOptionPane.showMessageDialog(parent, "Wrong data");
		}



	}

	void addPkFromFile(java.awt.event.ActionEvent evt) {
		int i = jList1.getSelectedIndex();
		jList1.setSelectedIndex(-1);
		trustList.remove(i);
		jButton7.setEnabled(false);
	}

	void generateNewKeypair(java.awt.event.ActionEvent evt) {
		//this.setModal(false);
		new GenerateKeyDialog(parent, true).setVisible(true);


	}

	void testConnector(java.awt.event.ActionEvent evt) {
		jTextField13.setText("http://bodoni.lib.liv.ac.uk:8080/AnnotationConnector/services/AnnotationServer");
	}

	void testSRW(java.awt.event.ActionEvent evt) {


	}

	/** Closes the dialog */
	void closeDialog() {
		setVisible(false);
		dispose();
	}


	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JCheckBox jCheckBox5;
	private javax.swing.JCheckBox jCheckBox6;
	private javax.swing.JCheckBox jCheckBox7;
	private javax.swing.JCheckBox jCheckBox8;
	
	///SAM
	private javax.swing.JCheckBox jCheckBoxBib;
	///
	
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JPasswordField jPasswordField4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField13;
	private javax.swing.JTextField jTextField14;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	// End of variables declaration

	///SAM
	boolean serverChanged = false;
	///
}
