/*******************************************************************************
 *
 *  * Copyright (C) 2007, 2010 - The University of Liverpool
 *  * This program is free software; you can redistribute it and/or modify it under the terms
 *  * of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License,
 *  * or (at your option) any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 *  * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *  * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *  *
 *  * Author: Fabio Corubolo
 *  * Email: corubolo@gmail.com
 * 
 *******************************************************************************/



package uk.ac.liv.c3connector.ui;

import java.text.DateFormat;

import javax.swing.JTextArea;

import uk.ac.liv.c3connector.AnnotationModel;
import uk.ac.liv.c3connector.FabAnnotation;

/**
 *
 * This is a simple visual dialog (created with Matisse) to show the different properties of an annotation in an organized way.
 *
 * @author  fabio
 */
public class AnnotationProperties extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private FabAnnotation fa;
	/** Creates new form AnnotationProperties */
	public AnnotationProperties(java.awt.Frame parent, boolean modal, FabAnnotation fa) {
		super(parent, modal);
		this.fa = fa;
		initComponents();
		setValues(fa);
	}

	/**
	 * @param fa2
	 */
	private void setValues(FabAnnotation fa2) {

		AnnotationModel at = fa.getAnn();

		if (fa.getSigner() != null) {
			if (fa.getVerificationStatus() == 1) {
				jTextField12.setText(fa.getSigner().getName());
				jTextField11.setText(fa.getSigner().getEmail());
				jTextField3.setText(fa.getSigner().getOrganisation());
			}
		} else {
			jTextField12.setText(at.getAuthor());
			jTextField11.setText("NOT SIGNED");
			jTextField3.setText("NOT SIGNED");
		}
		jTextField10.setText(at.getUserid());
		jTextField13.setText(at.getResourceUri());
		jCheckBox1.setSelected(fa.isSameUrl());
		if (at.getDocumentDigest()!=null)
			jTextField14.setText(at.getDocumentDigest());
		jCheckBox2.setSelected(fa.isSameCRC());
		if (at.getDocumentTextDigest()!=null)
			jTextField15.setText(at.getDocumentTextDigest());
		jCheckBox3.setSelected(fa.isSameTxtCRC());
		if (at.getLexicalSignature()!=null) {
			jTextField16.setText(at.getLexicalSignature());
			jCheckBox4.setSelected(fa.isSameLs());

		}
		jCheckBox1.setEnabled(false);
		jCheckBox2.setEnabled(false);
		jCheckBox3.setEnabled(false);
		jCheckBox4.setEnabled(false);
		jTextField17.setText(DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.MEDIUM, getLocale()).format(at.getDateModified()));
		jTextField18.setText(at.getApplication());
		if (at.getAnnotationBody()!=null) {
			String testo = at.getAnnotationBody();

			//			SAXBuilder b = new SAXBuilder();
			//			Document d;
			//			try {
			//				d = b.build(new StringReader (at.getAnnotationBody()));
			//				XMLOutputter o = new XMLOutputter (Format.getPrettyFormat());
			//				testo = o.outputString(d);
			//
			//			} catch (JDOMException e) {
			//				// TODO Auto-generated catch block
			//				e.printStackTrace();
			//			} catch (IOException e) {
			//				// TODO Auto-generated catch block
			//				e.printStackTrace();
			//			}
			//
			JTextArea ta = new JTextArea(testo);
			//System.out.println("aa");
			jScrollPane1.setViewportView(ta);
			//			jScrollPane1.validate();
			//			System.out.println(ta.getText());
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jTextField13 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jTextField14 = new javax.swing.JTextField();
		jTextField15 = new javax.swing.JTextField();
		jTextField16 = new javax.swing.JTextField();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jPanel3 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		jTextField17 = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		jTextField18 = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Annotation properties");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Author"));
		jLabel4.setText("Name");

		jTextField11.setEditable(false);
		jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField11focus(evt);
			}
		});

		jLabel18.setText("E-mail");

		jTextField3.setEditable(false);

		jLabel17.setText("Organisation");

		jTextField10.setEditable(false);

		jLabel5.setText("Userid");

		jTextField12.setEditable(false);

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
								.add(jLabel4)
								.add(jLabel18)
								.add(jLabel5)
								.add(jLabel17))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
										.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
										.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
										.add(jTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
										.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
										.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel4)
								.add(jTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel18))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jLabel17))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel5)))
		);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Annotated Resource"));
		jLabel6.setText("URI");

		jTextField13.setEditable(false);

		jLabel7.setText("MD5");

		jLabel8.setText("Text MD5");

		jLabel9.setText("Lexical signature");

		jTextField14.setEditable(false);

		jTextField15.setEditable(false);

		jTextField16.setEditable(false);

		jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));

		jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
		jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel7)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel8)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel9))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jCheckBox1)
										.add(jCheckBox2)
										.add(jCheckBox3)
										.add(jCheckBox4))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
												.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
												.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
												.add(jTextField15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
												.add(jTextField16, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
												.addContainerGap())
		);
		jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2Layout.createSequentialGroup()
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel6)
								.add(jTextField13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jCheckBox1))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel7)
										.add(jTextField14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jCheckBox2))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jLabel8)
												.add(jTextField15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jCheckBox3))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
														.add(jLabel9)
														.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jTextField16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(jCheckBox4))))
		);

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Annotation"));
		jLabel10.setText("Modification date");

		jTextField17.setEditable(false);

		jLabel11.setText("Application");

		jTextField18.setEditable(false);

		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel12.setText("Content");

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
								.add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
								.add(jLabel12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
								.add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3Layout.createSequentialGroup()
										.add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
												.add(jLabel11)
												.add(jLabel10))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
														.add(jTextField18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
														.add(jTextField17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))
														.addContainerGap())
		);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel3Layout.createSequentialGroup()
						.add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel10)
								.add(jTextField17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel11)
										.add(jTextField18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel12)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
										.addContainerGap())
		);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
								.add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jLabel1)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		pack();
	}// </editor-fold>

	void jTextField11focus(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		//        java.awt.EventQueue.invokeLater(new Runnable() {
		//            public void run() {
		//                new AnnotationProperties(new javax.swing.JFrame(), true).setVisible(true);
		//            }
		//        });
	}

	// Variables declaration - do not modify
	javax.swing.JCheckBox jCheckBox1;
	javax.swing.JCheckBox jCheckBox2;
	javax.swing.JCheckBox jCheckBox3;
	javax.swing.JCheckBox jCheckBox4;
	javax.swing.JLabel jLabel1;
	javax.swing.JLabel jLabel10;
	javax.swing.JLabel jLabel11;
	javax.swing.JLabel jLabel12;
	javax.swing.JLabel jLabel17;
	javax.swing.JLabel jLabel18;
	javax.swing.JLabel jLabel4;
	javax.swing.JLabel jLabel5;
	javax.swing.JLabel jLabel6;
	javax.swing.JLabel jLabel7;
	javax.swing.JLabel jLabel8;
	javax.swing.JLabel jLabel9;
	javax.swing.JPanel jPanel1;
	javax.swing.JPanel jPanel2;
	javax.swing.JPanel jPanel3;
	javax.swing.JScrollPane jScrollPane1;
	javax.swing.JTextField jTextField10;
	javax.swing.JTextField jTextField11;
	javax.swing.JTextField jTextField12;
	javax.swing.JTextField jTextField13;
	javax.swing.JTextField jTextField14;
	javax.swing.JTextField jTextField15;
	javax.swing.JTextField jTextField16;
	javax.swing.JTextField jTextField17;
	javax.swing.JTextField jTextField18;
	javax.swing.JTextField jTextField3;
	// End of variables declaration

}
