package uk.ac.liv.c3connector.ui;


///SAM: using StartupWizard's code


import java.awt.Component;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Random;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

import uk.ac.liv.c3connector.DistributedPersonalAnnos;
import uk.ac.liverpool.fab4.Fab4utils;
import uk.ac.liverpool.fab4.PersonalAnnos;


public class Authenticator extends javax.swing.JDialog{


	public static boolean CANCEL = false;
	DistributedPersonalAnnos da;
	public final static boolean LOGIN = true;
	public final static boolean SIGNUP = !LOGIN;
	private java.awt.Frame myparent;
	private boolean mymodal;
	
	public static boolean running = false;

	//private static final long serialVersionUID = 6532313365019485552L;
	
	public Authenticator(DistributedPersonalAnnos da, java.awt.Frame parent, boolean modal, boolean logSign) {
		super(parent, modal);
		
		myparent = parent;
		mymodal = modal;
		
		this.da = da;
		
//		initComponents();
		if(logSign == Authenticator.LOGIN )
			login();
		else
			signUp();

		if (Fab4utils.getJavaVersion()>=1.5f)
			setAlwaysOnTop(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	
	//SAM have changed inside the code (for more authentication options) and name of var names (for easier understanding)
	
	private void login(){
		jLogPanel1 = new javax.swing.JPanel();
		jLogLabel1 = new javax.swing.JLabel();
		
		jLogLabel_username = new javax.swing.JLabel();
		jLogLabel_pass = new javax.swing.JLabel();
		
		
		jLogPass_pass = new javax.swing.JPasswordField();
		
		jLogTextField_username = new javax.swing.JTextField();
		
		jLogLabel5 = new javax.swing.JLabel();
		jLogTextField12 = new javax.swing.JTextField();
		jLogButton1 = new javax.swing.JButton();
		jLogButton2_cancel = new javax.swing.JButton();
		jLogButtonSignUp = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		jLogLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		//jLabel1.setText("Please specify some information for the annotations.\n \nIf you prefer not to do so, press \"later\" and you will become an anonymous reviewer");
//		jLogLabel1.setText("Login... The following username is your username in private mode.\n You may keep or change it.");

//		jLogLabel1.setText("Login... ");
		
		///SAM: TODO I'm not yet thinking about anonymous annos ///
		
		jLogLabel_username.setText("Username:");
		
		jLogLabel_pass.setText("Password:");
		
		jLogTextField_username.setText(DistributedPersonalAnnos.userid);
		
		jLogTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focusLog();
			}
		});
		
		jLogPass_pass.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focusLog();
			}
		});
				
		jLogTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focusLog();
			}
		});
		
		jLogTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focusLog();}});
		
		jLogPass_pass.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focusLog();}});
				
		
		jLogTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focusLog();}});

		jLogLabel5.setText("User identifier:");
		jLogLabel5.setVisible(false);
		jLogTextField12.setVisible(false);
		
		jLogButton1.setText("OK");
		jLogButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jLogButton1ActionPerformed(evt);
			}
		});

		jLogButtonSignUp.setText("Sign up");
		jLogButtonSignUp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jLogSignUpButtActionPerformed(evt);
			}
		});
		
		//jButton2_later.setText("later");
		jLogButton2_cancel.setText("Go private");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jLogPanel1);
		jLogPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//				.add(jLogLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
								/*.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
												.add(jPanel1Layout.createSequentialGroup()
														.add(39, 39, 39)
														.add(jLabel18_email)														
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)														)
														.add(jLabel4_name)
											)
														
														.add(jLabel17_org)
									)*/
														
									.add(jLogLabel_username)
									.add(jLogLabel_pass)
									
									.add(jLogLabel5)
							)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
																.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
																		
																		.add(jLogButtonSignUp)
																		.add(jLogButton2_cancel)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
																		
																		.add(jLogButton1)
																		)
																		.add(jLogTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		/*.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField3_email, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jTextField10_org, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		*/
																		
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jLogTextField_username, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jLogPass_pass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		/*.add(org.jdesktop.layout.GroupLayout.TRAILING, jPass_cpass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField11_name, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		
																		.add(jTextField_aff, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField_des, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)*/
																		)
																		
																		
																		.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						/*.add(jLogLabel1)
						.add(22, 22, 22)
						*/
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLogTextField_username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLogLabel_username))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLogPass_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLogLabel_pass))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						/*.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jPass_cpass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_cpass))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField11_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel4_name))
								.add(6, 6, 6)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField3_email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel18_email))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jTextField10_org, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jLabel17_org))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField_aff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_aff))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField_des, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_des))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						*/		
												
												
												.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLogTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLogLabel5))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jLogButton1)
																.add(jLogButton2_cancel)
																.add(jLogButtonSignUp)
																)
																.addContainerGap())
		);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jLogPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jLogPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		jLogButton1.setEnabled(false);
		//jButton1.setToolTipText("fill in the fields above, at least the required ones, or press later");
		jLogButton1.setToolTipText("fill in the fields above to log in to the public annotations");
		
		jLogButton2_cancel.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				cancelPublic();
			}			

		});
		
		setTitle("Log in...");
		pack();

	}
	
	private void signUp() {
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		
		jLabel_username = new javax.swing.JLabel();
		jLabel_pass = new javax.swing.JLabel();
		jLabel_cpass = new javax.swing.JLabel();
		//jLabel_aff = new javax.swing.JLabel();
		jLabel_des = new javax.swing.JLabel();
		
		jPass_pass = new javax.swing.JPasswordField();
		jPass_cpass = new javax.swing.JPasswordField();
		jTextField_username = new javax.swing.JTextField();
		jTextField_des = new javax.swing.JTextField();
		//jTextField_aff = new javax.swing.JTextField();
		
		jLabel4_name = new javax.swing.JLabel();
		jTextField3_email = new javax.swing.JTextField();
		jLabel17_org = new javax.swing.JLabel();
		jTextField10_org = new javax.swing.JTextField();
		jLabel18_email = new javax.swing.JLabel();
		jTextField11_name = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2_later = new javax.swing.JButton();

		///SAM
		System.out.println("test! :D");
		///
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		//jLabel1.setText("Please specify some information for the annotations.\n \nIf you prefer not to do so, press \"later\" and you will become an anonymous reviewer");
//		jLabel1.setText("Sign in... The following username is your username in private mode.\n You may keep or change it.");
//		jLabel1.setText("Sign in...");
		///SAM: TODO I'm not yet thinking about anonymous annos ///
		
		jLabel_username.setText("Username*:");
		
		jLabel_pass.setText("Password*:");
		jLabel_cpass.setText("Confirm password*:");
		
		jLabel4_name.setText("Name*:");

		jLabel17_org.setText("Affiliation*:");

		jLabel18_email.setText("E-mail*:");
		
		//jLabel_aff.setText("Affiliation:");
		jLabel_des.setText("A brief description:");
		
		jTextField10_org.setText(DistributedPersonalAnnos.organisation);
		jTextField11_name.setText(DistributedPersonalAnnos.author);
		jTextField3_email.setText(DistributedPersonalAnnos.email);
		jTextField_username.setText(DistributedPersonalAnnos.userid);

		jTextField11_name.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		/*jTextField_aff.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});*/
		
		jTextField_des.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		jPass_pass.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		jPass_cpass.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		
		jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		jTextField10_org.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		jTextField3_email.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		jTextField3_email.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		jTextField10_org.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		jTextField11_name.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		jTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		/*jTextField_aff.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});*/
		
		jTextField_des.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		jPass_pass.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		jPass_cpass.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		
		
		jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});

		jLabel5.setText("User identifier:");
		jLabel5.setVisible(false);
		jTextField12.setVisible(false);
		jButton1.setText("Done");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		//jButton2_later.setText("later");
		jButton2_later.setText("Go private");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//				.add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
								/*.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
												.add(jPanel1Layout.createSequentialGroup()
//														.add(39, 39, 39)
*/																												
//														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)														
//														)
														.add(jLabel18_email)
														
														.add(jLabel4_name)
//														)
														.add(jLabel17_org)
//														)
														
														.add(jLabel_username)
														.add(jLabel_pass)
														.add(jLabel_cpass)
														//.add(jLabel_aff)
														.add(jLabel_des)
														
														.add(jLabel5))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
																.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
																		
																		.add(jButton2_later)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
																		
																		.add(jButton1)
																		)
																		.add(jTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField_username, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jPass_pass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jPass_cpass, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jTextField11_name, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField3_email, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jTextField10_org, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		
																		
																		//.add(jTextField_aff, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField_des, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		)
																		
																		
																		.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						/*.add(jLabel1)
						.add(22, 22, 22)
						*/
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField_username, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_username))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jPass_pass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_pass))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jPass_cpass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_cpass))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField11_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel4_name))
//								.add(6, 6, 6)
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField3_email, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel18_email))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField10_org, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel17_org))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												
						/*.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField_aff, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_aff))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)*/
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField_des, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)								
								.add(jLabel_des))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								
												
												
												.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel5))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jButton1)
																.add(jButton2_later)
																)
																.addContainerGap())
		);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		jButton1.setEnabled(false);
		//jButton1.setToolTipText("fill in the fields above, at least the required ones, or press later");
		jButton1.setToolTipText("fill in the fields above, at least the required ones");
		
		jButton2_later.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				cancel();
			}

		});
		
		setTitle("Sign up...");
		pack();
	}// </editor-fold>

	/**
	 * 
	 */
	protected void cancel() {
		//FIXME I want it to be 'anonymous' or so, but for now, I only exit!
		
		//System.exit(0);
		dispose();
		Authenticator.CANCEL = true; //in order to stop reloading
		Authenticator.running = false;
		//da.notify();
		
		/*JOptionPane.showMessageDialog(this, "You can enter your data later from the preferences\n(go to Edit -> Preferences)\n", "later...", JOptionPane.INFORMATION_MESSAGE);
		DistributedPersonalAnnos.userid = System.getProperty("user.name")+" "+new Random().nextInt(1000);
		DistributedPersonalAnnos.author = "Demo user";
		DistributedPersonalAnnos.email =  "example@email.com";
		DistributedPersonalAnnos.organisation = "Default Organisation";
		da.savePrefs();
		dispose();*/

	}

	private void cancelPublic() {		
		dispose();
		Authenticator.CANCEL = true; //in order to stop reloading
		Authenticator.running = false;
		//da.notify();
	}
	
	
	void focus() {
	
		if (//jTextField10.getText().length()>0 &&
				jTextField11_name.getText().length()>0 &&
				jTextField10_org.getText().length()>0 &&
				jTextField3_email.getText().length()>0 &&
				jTextField_username.getText().length() >0 &&
				jPass_pass.getPassword().length >0 && 
				jPass_cpass.getPassword().length >0 
				)
			jButton1.setEnabled(true);
		else jButton1.setEnabled(false);

	}
	
	void focusLog() {

		//FIXME commented for now.
		if (//jTextField10.getText().length()>0 &&				
				jLogTextField_username.getText().length() >0 &&
				jLogPass_pass.getPassword().length >0 
				)
			jLogButton1.setEnabled(true);
		else jLogButton1.setEnabled(false);
	}

	void jLogSignUpButtActionPerformed(java.awt.event.ActionEvent evt) {
		
		setVisible(false);
		//setEnabled(false);
		Authenticator au = new Authenticator(da, myparent, mymodal, Authenticator.SIGNUP);
		au.setAlwaysOnTop(true);
		au.setLocationRelativeTo(null);
		au.setVisible(true);
		dispose();
		//signUp();
	}
	
	void jLogButton1ActionPerformed(java.awt.event.ActionEvent evt) { //log in
		
		
		//TODO: I didnt change private username here! will savePrefs do it? However, the old ones don't change
				
		///TODO not secure at all! just make it run for now:
		char[] pas = jLogPass_pass.getPassword();
				
		String pass = String.valueOf(pas);
		String username = jLogTextField_username.getText();
		
		HashMap<String,String> state_info = da.isAuthenticated(username, pass);
		int state = Integer.parseInt(state_info.get("state"));
		
		if( state == 0){ //if ok
			
			Arrays.fill(pas,'0');
			if( !DistributedPersonalAnnos.userid.equals(username)){
				String msg = "Logged in. Your private username also changed to: "+jLogTextField_username.getText()+"\n";
				JOptionPane.showMessageDialog(this, msg, "Logged in...", JOptionPane.INFORMATION_MESSAGE);
			}
			DistributedPersonalAnnos.userid = username;
			DistributedPersonalAnnos.pass = pass;
			
			DistributedPersonalAnnos.author = state_info.get("name");
			DistributedPersonalAnnos.email = state_info.get("email");
			DistributedPersonalAnnos.organisation = state_info.get("aff");			
			
			Authenticator.running = false;
			da.savePrefs();
			dispose();
			//da.notify();
			
		}
		else{ //a problem
			
			if(state == 1){ //wrong pass
				Arrays.fill(pas,'0');
				String msg = "Wrong password. Try again.";
				JOptionPane.showMessageDialog(this, msg, "Try again...", JOptionPane.INFORMATION_MESSAGE);
				jLogPass_pass.setText(null);
			}
			else if(state == 2){ //no such username
				Arrays.fill(pas,'0');
				String msg = "No such username. Try again.";
				JOptionPane.showMessageDialog(this, msg, "Try again...", JOptionPane.INFORMATION_MESSAGE);
				jLogTextField_username.setText(null);
			}
			else{ //an exception in server
				Arrays.fill(pas,'0');
				String msg = "Sorry, there is a problem with server. Please try later.";
				JOptionPane.showMessageDialog(this, msg, "Try later...", JOptionPane.INFORMATION_MESSAGE);
				Authenticator.running = false;
				dispose();
			}
			
			//setVisible(false);			
			//new Authenticator(da, myparent, mymodal, Authenticator.LOGIN).setVisible(true);
		}
		
		
	}
	
	void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //sign up
		//11 3 10 12

		//FIXME here
		String name = jTextField11_name.getText();
		String email = jTextField3_email.getText();
		String aff = jTextField10_org.getText();
		String des = jTextField_des.getText();
		String username = jTextField_username.getText(); //System.getProperty("user.name")+"-"+new Random().nextInt(1000);
		 
		//= System.getProperty("user.name")+"-"+new Random().nextInt(1000); //SAM: for private annos, no problem! When copying to public, this will be replaced with real username
				
		
		///not secure at all! just make it run for now:
		char[] pas = jPass_pass.getPassword();
		char[] cpas = jPass_cpass.getPassword();		
		String pass = String.valueOf(pas);
		String cpass = String.valueOf(cpas);		
		
		if( pass.equals(cpass) ){
			
			int state = da.createNewUser(username, pass, email, name, des, aff);
			
			
			switch(state){
			
			case 0: //ok
				
				if( !DistributedPersonalAnnos.userid.equals(username)){
					String msg = "Signed in. Your private username also changed to: "+username+"\n";
					JOptionPane.showMessageDialog(this, msg, "Logged in...", JOptionPane.INFORMATION_MESSAGE);
				}
				
				DistributedPersonalAnnos.pass = pass;
				DistributedPersonalAnnos.userid = username;
				DistributedPersonalAnnos.author = name;
				DistributedPersonalAnnos.email = email;
				DistributedPersonalAnnos.organisation = aff;
				
				Authenticator.running = false;
				da.savePrefs();
				dispose();
				//da.notify();
				break;
			case 1: //username exists
				JOptionPane.showMessageDialog(this, "Username exists, please type again\n", "Try again...", JOptionPane.INFORMATION_MESSAGE);
				jTextField_username.setText(null);
				break;
			case 2: //email exists
				JOptionPane.showMessageDialog(this, "An account with this email exists, please try again\n", "Try again...", JOptionPane.INFORMATION_MESSAGE);
				jTextField3_email.setText(null);
				break;
			case 3: //an exception
				String m = "Sorry, there is a problem with server. Please try later.";
				JOptionPane.showMessageDialog(this, m, "Try later...", JOptionPane.INFORMATION_MESSAGE);
				Authenticator.running = false;
				dispose();
				break;
			}
		}
		else{
			JOptionPane.showMessageDialog(this, "Confirmed password does not match the provided one, please type again\n", "Fail...", JOptionPane.INFORMATION_MESSAGE);
			jPass_cpass.setText(null);
			
			//setVisible(false);			
			//new Authenticator(da, myparent, mymodal, Authenticator.SIGNUP).setVisible(true);
		}
						
		//authenticate, check username, display appropriate msgs, create user
		
		Arrays.fill(pas,'0');
		Arrays.fill(cpas,'0');
			
	}


	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;	
	private javax.swing.JButton jButton2_later;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel17_org;
	private javax.swing.JLabel jLabel18_email;
	private javax.swing.JLabel jLabel4_name;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField10_org;
	private javax.swing.JTextField jTextField11_name;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField3_email;
	
	///SAM	
	private javax.swing.JLabel jLabel_username;
	private javax.swing.JLabel jLabel_pass;
	private javax.swing.JLabel jLabel_cpass;
	//private javax.swing.JLabel jLabel_aff;
	private javax.swing.JLabel jLabel_des;
	private javax.swing.JTextField jTextField_username;
	//private javax.swing.JTextField jTextField_aff;
	private javax.swing.JTextField jTextField_des;
	private javax.swing.JPasswordField jPass_pass;
	private javax.swing.JPasswordField jPass_cpass;
	///
	
	///login:
	private javax.swing.JButton jLogButton1;	
	private javax.swing.JButton jLogButton2_cancel;
	private javax.swing.JLabel jLogLabel1;
	private javax.swing.JLabel jLogLabel5;
	private javax.swing.JPanel jLogPanel1;
	private javax.swing.JTextField jLogTextField12;
	private javax.swing.JButton jLogButtonSignUp;
	private javax.swing.JLabel jLogLabel_username;
	private javax.swing.JLabel jLogLabel_pass;
	private javax.swing.JTextField jLogTextField_username;
	private javax.swing.JPasswordField jLogPass_pass;
	// End of variables declaration
	
	
	///SAM:
	public void init(java.awt.Frame parent){
		Object[] possibilities = null;//{"ham", "spam", "yam"};
		
		ImageIcon icon = new ImageIcon();
		
		String s = (String)JOptionPane.showInputDialog(parent,
					"Complete the sentence:\n"
       + "\"Green eggs and...\"",
       "Customized Dialog",
       JOptionPane.PLAIN_MESSAGE,
       icon,
       possibilities,
       "ham");

		//If a string was returned, say so.
		if ((s != null) && (s.length() > 0)) {
		    //setLabel("Green eggs and... " + s + "!");
			System.out.println(s);
		    return;
		}

		//If you're here, the return value was null/empty.
		//setLabel("Come on, finish the sentence!");
		System.out.println("nok!");
		
	}

}
