/*******************************************************************************
 *
 *  * Copyright (C) 2007, 2010 - The University of Liverpool
 *  * This program is free software; you can redistribute it and/or modify it under the terms
 *  * of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License,
 *  * or (at your option) any later version.
 *  * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 *  * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *  * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *  *
 *  * Author: Fabio Corubolo
 *  * Email: corubolo@gmail.com
 * 
 *******************************************************************************/



package uk.ac.liv.c3connector.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Random;

import javax.swing.JOptionPane;

import uk.ac.liv.c3connector.DistributedPersonalAnnos;
import uk.ac.liverpool.fab4.Fab4utils;

/**
 *
 * This dialog represent the wizard that is displayed the first time the application is started.
 *
 * @author  fabio
 */
public class StartupWizard extends javax.swing.JDialog {

	/**
	 * 
	 */
	DistributedPersonalAnnos da;
	private static final long serialVersionUID = 6532313365019485552L;
	/** Creates new form StartupWizard */
	public StartupWizard(DistributedPersonalAnnos da, java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.da = da;
		initComponents();

		if (Fab4utils.getJavaVersion()>=1.5f)
			setAlwaysOnTop(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("Please specify some information for the annotations.\n If you prefer not to do so, press \"later\"");

		jLabel4.setText("Name:");

		jLabel17.setText("Organisation:");

		jLabel18.setText("E-mail:");

		jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
			@Override
			public void focusLost(java.awt.event.FocusEvent evt) {
				focus();
			}
		});
		jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});
		jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyPressed(KeyEvent e) {focus();}});

		jLabel5.setText("User identifier:");
		jLabel5.setVisible(false);
		jTextField12.setVisible(false);
		jButton1.setText("Done...");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("later");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
												.add(jPanel1Layout.createSequentialGroup()
														.add(39, 39, 39)
														.add(jLabel18)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
														.add(jLabel4))
														.add(jLabel17))
														.add(jLabel5))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
																.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
																		.add(jButton2)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(jButton1))
																		.add(jTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(jTextField10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
																		.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.add(jLabel1)
						.add(22, 22, 22)
						.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel4))
								.add(6, 6, 6)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel18))
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jLabel17))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel5))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 46, Short.MAX_VALUE)
														.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jButton1)
																.add(jButton2))
																.addContainerGap())
		);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
		);
		jButton1.setEnabled(false);
		jButton1.setToolTipText("fill in all the fields above or press later");
		jButton2.addActionListener(new ActionListener() {

			public void actionPerformed(ActionEvent e) {
				cancel();
			}

		});
		setTitle("Your details...");
		pack();
	}// </editor-fold>

	/**
	 * 
	 */
	protected void cancel() {
		JOptionPane.showMessageDialog(this, "You can enter your data later from the preferences\n(go to Edit -> Preferences)\n", "later...", JOptionPane.INFORMATION_MESSAGE);
		DistributedPersonalAnnos.userid = System.getProperty("user.name")+" "+new Random().nextInt(1000);
		DistributedPersonalAnnos.author = "Demo user";
		DistributedPersonalAnnos.email =  "example@email.com";
		DistributedPersonalAnnos.organisation = "Default Organisation";
		da.savePrefs();
		dispose();

	}

	void focus() {

		if (//jTextField10.getText().length()>0 &&
				jTextField11.getText().length()>0 &&
				jTextField10.getText().length()>0 &&
				jTextField3.getText().length()>0)
			jButton1.setEnabled(true);
		else jButton1.setEnabled(false);

	}

	void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//11 3 10 12

		DistributedPersonalAnnos.author = jTextField11.getText();
		DistributedPersonalAnnos.email = jTextField3.getText();
		DistributedPersonalAnnos.organisation = jTextField10.getText();
		DistributedPersonalAnnos.userid =System.getProperty("user.name")+"-"+new Random().nextInt(1000);
		da.savePrefs();
		dispose();


	}


	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration

}
